pipeline {
    agent any

    tools {
        maven 'maven 3.8.6'
    }

    stages {
        stage('build') {
            when {
                changeset '**/worker/**'
            }
            steps {
                echo 'Running build stage'
                dir('worker') {
                    sh 'mvn compile'
                }
            }
        }
        stage('test') {
            when {
                changeset '**/worker/**'
            }
            steps {
                echo 'Running test stage'
                dir('worker') {
                    sh 'mvn clean test'
                }
            }
        }
        stage('package') {
            when {
                branch 'master'
                changeset '**/worker/**'
            }
            steps {
                echo 'Running package stage'
                dir('worker') {
                    sh 'mvn package -DskipTests'
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
            echo 'Pipeline completed'
        }
    }
}
