pipeline {
    agent {
        docker {
            image 'maven:3.8.1-adoptopenjdk-11'
            args '-v $HOME/.m2:/root/.m2'
        }
    }

    stages {
        stage('build') {
            when {
                changeset '**/worker/**'
            }
            steps {
                echo 'Running build stage'
                dir('worker') {
                    sh 'mvn compile'
                }
            }
        }
        stage('test') {
            when {
                changeset '**/worker/**'
            }
            steps {
                echo 'Running test stage'
                dir('worker') {
                    sh 'mvn clean test'
                }
            }
        }
        stage('docker-package') {
            when {
                branch 'master'
                changeset '**/worker/**'
            }
            steps {
                echo 'Running package stage'
                script {
                    docker.withRegistry('https://index.docker.io/v1', 'dockerlogin') {

                        def workerImage = docker.build("rvlkr/worker:v${env.BUILD_ID}", "./worker")
                        workerImage.push()
                        workerImage.push("${env.BRANCH_NAME}")
                    }
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
            echo 'Pipeline completed'
        }
    }
}
